"""
SolidWorks 离心风机叶轮参数化生成器

建模流程：
1. 后盘（轮盘）— 旋转凸台
2. 前盘（轮盖）— 旋转凸台
3. 叶片 3D 样条曲线（轮盘侧+轮盖侧）
4. 放样曲面 → 加厚
5. 圆周阵列

依赖: pywin32 (Windows only)
备用：VBA 宏（跨平台）
"""

import os
import math

from .params import ImpellerDesignResult
from .blades import generate_blade_profile, generate_3d_blade, CurveType

try:
    import pythoncom
    import win32com.client as win32
    HAS_PYWIN32 = True
except ImportError:
    HAS_PYWIN32 = False


# ═══════════════════════════════════════════════════════════════
# VBA 宏生成（跨平台，可审计）
# ═══════════════════════════════════════════════════════════════


def generate_vba_macro(design: ImpellerDesignResult) -> str:
    """
    生成 SolidWorks VBA 宏

    宏包含完整的叶轮建模步骤，在 SolidWorks 中：
      工具 → 宏 → 运行 → 选择此文件

    步骤：
    1. 后盘旋转体（轮盘）
    2. 前盘旋转体（轮盖）
    3. 叶片 3D 样条曲线（上下两条）
    4. 放样曲面（生成单个叶片曲面）
    5. 圆周阵列 Z 个叶片
    """
    p = design

    # ── 数值准备 ──
    r_hub = p.dh / 2.0
    r1 = p.D1 / 2.0
    r2 = p.D2 / 2.0
    r0 = p.D0 / 2.0
    disk_t = _disk_thick(p)
    cover_t = _cover_thick(p)
    z_up = p.b1       # 轮盖侧高度
    z_edge = p.b1 * 0.3  # 外缘收口

    def m(v):
        """mm → m (VBA 用 meters)"""
        return f"{v / 1000.0:.6f}"

    # ── 叶片型线（20 点） ──
    profile = generate_blade_profile(r1, r2, p.beta1, p.beta2, n_points=20)

    # 下缘曲线赋值（z=0）
    lower_assign = []
    for i, pt in enumerate(profile):
        lower_assign.append(
            f"  lp({i * 3}) = {pt['x'] / 1000.0:.6f}: "
            f"lp({i * 3 + 1}) = {pt['y'] / 1000.0:.6f}: lp({i * 3 + 2}) = 0"
        )

    # 上缘曲线赋值（z=b1）
    upper_assign = []
    for i, pt in enumerate(profile):
        upper_assign.append(
            f"  up({i * 3}) = {pt['x'] / 1000.0:.6f}: "
            f"up({i * 3 + 1}) = {pt['y'] / 1000.0:.6f}: "
            f"up({i * 3 + 2}) = {p.b1 / 1000.0:.6f}"
        )

    n = len(profile)

    macro = f"""' SolidWorks VBA Macro - Centrifugal Fan Impeller
' Generated by solidworks-parametric v0.1.0
'
' Design: Q={p.input_params.Q:.0f}m3/h  P={p.input_params.P:.0f}Pa  n={p.input_params.n:.0f}rpm
' Output: D2={p.D2:.0f}mm  D1={p.D1:.0f}mm  Z={p.Z}  b1={p.beta1:.1f}deg  b2={p.beta2:.1f}deg
'
' Instructions: SolidWorks -> Tools -> Macro -> Run
' ============================================================

Dim swApp As Object
Dim Part As Object
Dim skMgr As Object
Dim featMgr As Object
Dim boolStat As Boolean

Sub main()
    Set swApp = Application.SldWorks
    Set Part = swApp.NewDocument("", 0, 0, 0)
    swApp.Visible = True
    Set skMgr = Part.SketchManager
    Set featMgr = Part.FeatureManager

    ' ============================================================
    ' Step 1: Rear disk (revolution)
    ' ============================================================
    skMgr.InsertSketch True

    Part.CreateLine2 0, 0, 0, {m(r_hub)}, 0, 0
    Part.CreateLine2 {m(r_hub)}, 0, 0, {m(r_hub)}, {m(disk_t)}, 0
    Part.CreateLine2 {m(r_hub)}, {m(disk_t)}, 0, {m(r1)}, {m(disk_t)}, 0
    Part.CreateLine2 {m(r1)}, {m(disk_t)}, 0, {m(r2)}, {m(disk_t * 0.6)}, 0
    Part.CreateLine2 {m(r2)}, {m(disk_t * 0.6)}, 0, {m(r2)}, 0, 0
    Part.CreateLine2 {m(r2)}, 0, 0, 0, 0, 0

    skMgr.InsertSketch True
    Part.ClearSelection2 True

    Part.Extension.SelectByID2 "", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, 0
    boolStat = featMgr.FeatureRevolve(True, False, False, False, False, 0, 0, 360#, 0, False, False, False)

    ' ============================================================
    ' Step 2: Front cover (revolution)
    ' ============================================================
    skMgr.InsertSketch True

    Part.CreateLine2 {m(r0)}, 0, 0, {m(r0)}, {m(cover_t)}, 0
    Part.CreateLine2 {m(r0)}, {m(cover_t)}, 0, {m(r1)}, {m(z_up)}, 0
    Part.CreateLine2 {m(r1)}, {m(z_up)}, 0, {m(r2)}, {m(z_edge)}, 0
    Part.CreateLine2 {m(r2)}, {m(z_edge)}, 0, {m(r2)}, 0, 0
    Part.CreateLine2 {m(r2)}, 0, 0, {m(r0)}, 0, 0

    skMgr.InsertSketch True
    Part.ClearSelection2 True
    Part.Extension.SelectByID2 "", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, 0
    boolStat = featMgr.FeatureRevolve(True, False, False, False, False, 0, 0, 360#, 0, False, False, False)

    ' ============================================================
    ' Step 3: Blade lower profile (z=0, disk side)
    ' ============================================================
    skMgr.Insert3DSketch True

    Dim lp(0 To {n * 3 - 1}) As Double
{chr(10).join(lower_assign)}

    Dim spline1 As Object
    Set spline1 = skMgr.CreateSpline(lp)
    skMgr.Insert3DSketch True

    ' ============================================================
    ' Step 4: Blade upper profile (z={m(p.b1)}, shroud side)
    ' ============================================================
    skMgr.Insert3DSketch True

    Dim up(0 To {n * 3 - 1}) As Double
{chr(10).join(upper_assign)}

    Dim spline2 As Object
    Set spline2 = skMgr.CreateSpline(up)
    skMgr.Insert3DSketch True

    ' ============================================================
    ' Step 5: Loft surface (1st blade)
    ' ============================================================
    Part.ClearSelection2 True
    boolStat = Part.Extension.SelectByID2("3DSketch1", "SKETCH", 0, 0, 0, False, 0, Nothing, 0)
    boolStat = Part.Extension.SelectByID2("3DSketch2", "SKETCH", 0, 0, 0, True, 0, Nothing, 0)

    ' Create surface loft
    Dim loftFeature As Object
    Set loftFeature = featMgr.InsertProtrusionBlend( _
        False, 0, False, True, 0, 0, 0, 0, 0, 0, 0, 0, False, False, False, 0)

    ' ============================================================
    ' Step 6: Circular pattern Z={p.Z}
    ' ============================================================
    Part.ClearSelection2 True
    boolStat = Part.Extension.SelectByID2("Blend1", "BODYFEATURE", 0, 0, 0, True, 0, Nothing, 0)
    Set patternFeat = featMgr.FeatureCircularPattern( _
        {p.Z}, 360#, False, False, False, "Blend1")

    Part.ViewZoomtofit2
    MsgBox "Centrifugal Fan Impeller" & vbCrLf & _
           "D2={p.D2:.0f}mm  Z={p.Z}  b2={p.beta2:.1f}deg  N={p.N_motor:.1f}kW", _
           vbInformation, "solidworks-parametric"
End Sub
"""
    return macro


def _disk_thick(p) -> float:
    return max(3.0, min(20.0, 4.0 + 0.005 * p.D2))


def _cover_thick(p) -> float:
    return max(2.0, min(15.0, 2.5 + 0.003 * p.D2))


# ═══════════════════════════════════════════════════════════════
# COM API 直接建模（Windows + SolidWorks 必需）
# ═══════════════════════════════════════════════════════════════


def _connect_sw(visible=True):
    pythoncom.CoInitialize()
    try:
        app = win32.GetActiveObject("SldWorks.Application")
    except Exception:
        app = win32.Dispatch("SldWorks.Application")
    app.Visible = visible
    return app


def build_impeller_sw(
    design: ImpellerDesignResult,
    output_path: str = "",
    visible: bool = True,
) -> str:
    """
    在 SolidWorks 中直接自动建模
    """
    if not HAS_PYWIN32:
        raise RuntimeError("Need pywin32 + Windows + SolidWorks")

    app = _connect_sw(visible)
    doc = app.NewDocument("", 0, 0.0, 0.0)
    part = doc

    try:
        p = design
        r_hub = p.dh / 2.0
        r1 = p.D1 / 2.0
        r2 = p.D2 / 2.0
        r0 = p.D0 / 2.0
        disk_t = _disk_thick(p)
        cover_t = _cover_thick(p)

        # Step 1: 后盘
        part.SketchManager.InsertSketch(True)
        lines = [
            (0, 0), (r_hub / 1000, 0),
            (r_hub / 1000, disk_t / 1000),
            (r1 / 1000, disk_t / 1000),
            (r2 / 1000, disk_t * 0.6 / 1000),
            (r2 / 1000, 0), (0, 0),
        ]
        for i in range(len(lines) - 1):
            part.CreateLine2(*lines[i], 0, *lines[i + 1], 0)
        part.SketchManager.InsertSketch(True)
        part.ClearSelection2(True)
        part.Extension.SelectByID2("", "SKETCHSEGMENT", 0, 0, 0, True, 0, None, 0)
        part.FeatureManager.FeatureRevolve(True, False, False, False, False, 0, 0, 360.0, 0, False, False, False)

        # Step 2: 前盖（轮盖）旋转体
        z_up = p.b1 / 1000.0        # 轮盖进口高度
        z_edge = p.b1 * 0.3 / 1000.0  # 外缘收口高度
        part.SketchManager.InsertSketch(True)
        lines2 = [
            (r0 / 1000.0, 0.0), (r0 / 1000.0, cover_t / 1000.0),
            (r1 / 1000.0, z_up), (r2 / 1000.0, z_edge),
            (r2 / 1000.0, 0.0), (r0 / 1000.0, 0.0),
        ]
        for i in range(len(lines2) - 1):
            part.CreateLine2(*lines2[i], 0, *lines2[i + 1], 0)
        part.SketchManager.InsertSketch(True)
        part.ClearSelection2(True)
        part.Extension.SelectByID2("", "SKETCHSEGMENT", 0, 0, 0, True, 0, None, 0)
        part.FeatureManager.FeatureRevolve(True, False, False, False, False, 0, 0, 360.0, 0, False, False, False)

        # Step 3: 叶片下缘 3D 样条（z=0，后盘侧）
        profile = generate_blade_profile(r1, r2, p.beta1, p.beta2, n_points=20)
        lower_pts = []
        for pt in profile:
            lower_pts.extend([pt["x"] / 1000.0, pt["y"] / 1000.0, 0.0])
        part.SketchManager.Insert3DSketch(True)
        part.SketchManager.CreateSpline(lower_pts)
        part.SketchManager.Insert3DSketch(True)

        # Step 4: 叶片上缘 3D 样条（z=b1，轮盖侧）
        upper_pts = []
        for pt in profile:
            upper_pts.extend([pt["x"] / 1000.0, pt["y"] / 1000.0, p.b1 / 1000.0])
        part.SketchManager.Insert3DSketch(True)
        part.SketchManager.CreateSpline(upper_pts)
        part.SketchManager.Insert3DSketch(True)

        # Step 5: 放样生成第一枚叶片
        part.ClearSelection2(True)
        part.Extension.SelectByID2("3DSketch1", "SKETCH", 0, 0, 0, False, 0, None, 0)
        part.Extension.SelectByID2("3DSketch2", "SKETCH", 0, 0, 0, True, 0, None, 0)
        part.FeatureManager.InsertProtrusionBlend(
            False, 0, False, True, 0, 0, 0, 0, 0, 0, 0, 0, False, False, False, 0
        )

        # Step 6: 圆周阵列 Z 个叶片
        part.ClearSelection2(True)
        part.Extension.SelectByID2("Blend1", "BODYFEATURE", 0, 0, 0, True, 0, None, 0)
        part.FeatureManager.FeatureCircularPattern(
            p.Z, 360.0, False, False, False, "Blend1"
        )

        part.ClearSelection2(True)

        if output_path:
            os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
            part.SaveAs(output_path)
            return output_path
        return ""
    except Exception as e:
        raise RuntimeError(f"SW modeling failed: {e}")


# ═══════════════════════════════════════════════════════════════
# 完整 Pipeline
# ═══════════════════════════════════════════════════════════════


def design_and_generate(
    Q: float, P: float, n: float,
    blade_type: str = "backward",
    material: str = "Q235B",
    output_dir: str = ".",
    gen_macro: bool = True,
    gen_model: bool = False,
) -> dict:
    """
    完整流程：设计 → 生成 VBA 宏（可选: SW 3D 模型）

    Returns:
        {"design": ..., "summary": ..., "macro_path": ..., "model_path": ...}
    """
    from .design import design_impeller
    from .params import ImpellerDesignInput

    inp = ImpellerDesignInput(Q=Q, P=P, n=n, blade_type=blade_type, material=material)
    design = design_impeller(inp)
    result = {"design": design, "summary": design.summary, "macro_path": None, "model_path": None}

    os.makedirs(output_dir, exist_ok=True)
    safe = f"Impeller_Q{Q:.0f}_P{P:.0f}_n{n:.0f}"

    if gen_macro:
        path = os.path.join(output_dir, f"{safe}.bas")
        with open(path, "w", encoding="utf-8") as f:
            f.write(generate_vba_macro(design))
        result["macro_path"] = path
        print(f"  ✅ VBA Macro: {path}")

    if gen_model and HAS_PYWIN32:
        path = os.path.join(output_dir, f"{safe}.SLDPRT")
        build_impeller_sw(design, output_path=path)
        result["model_path"] = path

    return result


# ═══════════════════════════════════════════════════════════════
# Test
# ═══════════════════════════════════════════════════════════════

if __name__ == "__main__":
    from .design import design_impeller
    from .params import ImpellerDesignInput

    inp = ImpellerDesignInput(Q=5000, P=2500, n=1450)
    design = design_impeller(inp)
    print(design.summary)

    macro = generate_vba_macro(design)
    with open("/tmp/impeller.bas", "w") as f:
        f.write(macro)
    print(f"\n✅ VBA macro: /tmp/impeller.bas ({len(macro)} chars, {macro.count(chr(10))} lines)")
