"""
SolidWorks 轴流风机参数化生成器

建模流程：
1. 轮毂（Hub）— 旋转凸台
2. 集流器/机壳（可选）
3. 各截面翼型 3D 样条曲线
4. 放样（Loft）生成单个叶片
5. 圆周阵列 Z 个叶片
6. 可选：轴孔/法兰接口特征

依赖: pywin32 (Windows only)
备用：VBA 宏（跨平台）
"""

import os
import math
from typing import Optional

from .params import AxialFanResult, BladeSection, AirfoilType
from .blades import (
    generate_airfoil_coords,
    generate_blade_loft_profile,
    export_sw_curve,
    export_loft_sections,
)

try:
    import pythoncom
    import win32com.client as win32
    HAS_PYWIN32 = True
except ImportError:
    HAS_PYWIN32 = False


# ═══════════════════════════════════════════════════════════════
# VBA 宏生成（跨平台，可审计）
# ═══════════════════════════════════════════════════════════════


def generate_vba_macro(design: AxialFanResult) -> str:
    """
    生成 SolidWorks VBA 宏

    宏包含完整的轴流叶轮建模步骤，在 SolidWorks 中：
      工具 → 宏 → 运行 → 选择此文件

    步骤：
    1. 轮毂旋转体
    2. 各截面翼型曲线（逐截面插入）
    3. 放样生成叶片
    4. 圆周阵列 Z 个叶片
    5. 可选：轴孔特征
    """
    p = design
    secs = p.sections

    if not secs:
        raise ValueError("设计结果无截面数据，无法生成宏")

    sections_data = []
    for idx, sec in enumerate(secs):
        # 生成该截面的翼型坐标
        upper, lower = generate_airfoil_coords(p.airfoil, 20, 20)

        # 合成为完整翼型截面
        airfoil_points = []
        for xu, yu in upper:
            airfoil_points.append((xu, yu))
        for xl, yl in reversed(lower):
            airfoil_points.append((xl, yl))

        sections_data.append({
            "idx": idx,
            "r": sec.r,
            "c": sec.c,
            "chi": sec.chi,
            "points": airfoil_points,
            "n_points": len(airfoil_points),
        })

    def m(v):
        """mm → m (VBA 用 meters)"""
        return f"{v / 1000.0:.6f}"

    # ── 生成各截面翼型点赋值 VBA 代码 ──
    section_assignments = []
    for sd in sections_data:
        r = sd["r"]
        c = sd["c"]
        chi = sd["chi"]
        chi_rad = math.radians(chi)
        n_pts = sd["n_points"]
        pts = sd["points"]

        assignments = []
        for i, (x_local, y_local) in enumerate(pts):
            xs = x_local * c
            ys = y_local * c
            x_sw = xs * math.cos(chi_rad)
            y_sw = r
            z_sw = xs * math.sin(chi_rad) + ys
            assignments.append(
                f"  sp{idx}({i * 3}) = {x_sw / 1000.0:.6f}: "
                f"sp{idx}({i * 3 + 1}) = {y_sw / 1000.0:.6f}: "
                f"sp{idx}({i * 3 + 2}) = {z_sw / 1000.0:.6f}"
            )

        section_assignments.append(
            f"' Section {sd['idx']}: r={sd['r']:.0f}mm  c={sd['c']:.0f}mm  chi={sd['chi']:.1f}°\n"
            f"Dim sp{sd['idx']}(0 To {n_pts * 3 - 1}) As Double\n"
            + "\n".join(assignments)
        )

    # ── 各截面曲线创建 ──
    section_splines = []
    for sd in sections_data:
        section_splines.append(
            f"  skMgr.Insert3DSketch True\n"
            f"  Dim spline{sd['idx']} As Object\n"
            f"  Set spline{sd['idx']} = skMgr.CreateSpline(sp{sd['idx']})\n"
            f"  skMgr.Insert3DSketch True"
        )

    # ── 放样选择 ──
    loft_selections = []
    for sd in sections_data:
        loft_selections.append(
            f"  boolStat = Part.Extension.SelectByID2(\"3DSketch{sd['idx'] + 1}\", "
            f"\"SKETCH\", 0, 0, 0, {loft_selections == []}, 0, Nothing, 0)"
        )

    hub_radius_m = p.r_hub / 1000.0
    hub_half_h_m = max(30, p.L * 0.3) / 1000.0  # 轮毂半长 (m)

    macro = f"""' SolidWorks VBA Macro - Axial Fan Impeller
' Generated by solidworks-parametric v0.1.0
'
' Design: Q={p.input_params.Q:.0f}m3/h  P={p.input_params.P:.0f}Pa  n={p.input_params.n:.0f}rpm
' Output: D={p.D:.0f}mm  d={p.d:.0f}mm  nu={p.nu:.3f}  Z={p.Z}
' Airfoil: {p.airfoil.value}  Circulation: {p.circulation_type.value}
'
' Instructions: SolidWorks -> Tools -> Macro -> Run
' ============================================================

Dim swApp As Object
Dim Part As Object
Dim skMgr As Object
Dim featMgr As Object
Dim boolStat As Boolean

Sub main()
    Set swApp = Application.SldWorks
    Set Part = swApp.NewDocument("", 0, 0, 0)
    swApp.Visible = True
    Set skMgr = Part.SketchManager
    Set featMgr = Part.FeatureManager

    ' ============================================================
    ' Step 1: Hub (body of revolution) — 轮毂旋转体
    ' ============================================================
    skMgr.InsertSketch True

    ' Hub profile: Z-axis as centerline
    Part.CreateLine2 0, 0, 0, {hub_radius_m:.6f}, 0, 0
    Part.CreateLine2 {hub_radius_m:.6f}, 0, 0, {hub_radius_m:.6f}, {hub_half_h_m:.6f}, 0
    Part.CreateLine2 {hub_radius_m:.6f}, {hub_half_h_m:.6f}, 0, 0, {hub_half_h_m:.6f}, 0
    Part.CreateLine2 0, {hub_half_h_m:.6f}, 0, 0, 0, 0

    ' Centerline axis
    Part.CreateLine2 0, {hub_half_h_m:.6f}, 0, 0, {-hub_half_h_m:.6f}, 0

    skMgr.InsertSketch True
    Part.ClearSelection2 True

    Part.Extension.SelectByID2 "", "SKETCHSEGMENT", 0, 0, 0, True, 0, Nothing, 0
    boolStat = featMgr.FeatureRevolve(True, False, False, False, False, 0, 0, 360#, 0, False, False, False)

    ' ============================================================
    ' Step 2: Blade sections (3D splines)
    ' ============================================================

{chr(10).join(section_assignments)}

    ' ============================================================
    ' Step 3: Create 3D splines for each section
    ' ============================================================

{chr(10).join(section_splines)}

    ' ============================================================
    ' Step 4: Loft — surface/blend between sections
    ' ============================================================
    Part.ClearSelection2 True

{chr(10).join(loft_selections)}

    ' Loft as thin feature (surface + thickness)
    ' Using InsertProtrusionBlend for loft
    Dim loftFeat As Object
    Set loftFeat = featMgr.InsertProtrusionBlend( _
        False, 0, False, True, 0, 0, 0, 0, 0, 0, 0, 0, False, False, False, 0)

    ' Add thickness if needed (thin feature)
    ' Set loftFeat = featMgr.InsertProtrusionThinBlend(...)

    ' ============================================================
    ' Step 5: Circular pattern — {p.Z} blades
    ' ============================================================
    Part.ClearSelection2 True
    boolStat = Part.Extension.SelectByID2("Blend1", "BODYFEATURE", 0, 0, 0, True, 0, Nothing, 0)
    Set patternFeat = featMgr.FeatureCircularPattern( _
        {p.Z}, 360#, False, False, False, "Blend1")

    Part.ViewZoomtofit2
    MsgBox "Axial Fan Impeller" & vbCrLf & _
           "D={p.D:.0f}mm  nu={p.nu:.2f}  Z={p.Z}  N={p.N_motor:.1f}kW" & vbCrLf & _
           "Airfoil: {p.airfoil.value}  Sections: {len(secs)}", _
           vbInformation, "solidworks-parametric"
End Sub
"""
    return macro


# ═══════════════════════════════════════════════════════════════
# COM API 直接建模（Windows + SolidWorks 必需）
# ═══════════════════════════════════════════════════════════════


def _connect_sw(visible=True):
    pythoncom.CoInitialize()
    try:
        app = win32.GetActiveObject("SldWorks.Application")
    except Exception:
        app = win32.Dispatch("SldWorks.Application")
    app.Visible = visible
    return app


def build_axial_sw(
    design: AxialFanResult,
    output_path: str = "",
    visible: bool = True,
) -> str:
    """
    在 SolidWorks 中直接自动建模（Windows only）
    """
    if not HAS_PYWIN32:
        raise RuntimeError("Need pywin32 + Windows + SolidWorks")

    app = _connect_sw(visible)
    doc = app.NewDocument("", 0, 0.0, 0.0)
    part = doc

    try:
        p = design
        # Hub profile
        part.SketchManager.InsertSketch(True)
        r_hub = p.r_hub / 1000.0
        hub_len = max(0.03, p.L / 1000.0 * 0.3)
        lines = [
            (0, 0), (r_hub, 0),
            (r_hub, hub_len),
            (0, hub_len), (0, -hub_len),
        ]
        for i in range(len(lines) - 1):
            part.CreateLine2(*lines[i], 0, *lines[i + 1], 0)
        part.SketchManager.InsertSketch(True)
        part.ClearSelection2(True)
        part.Extension.SelectByID2("", "SKETCHSEGMENT", 0, 0, 0, True, 0, None, 0)
        part.FeatureManager.FeatureRevolve(True, False, False, False, False, 0, 0, 360.0, 0, False, False, False)

        # Blade sections (simplified)
        for idx, sec in enumerate(p.sections):
            part.SketchManager.Insert3DSketch(True)
            upper, lower = generate_airfoil_coords(p.airfoil, 20, 20)
            chi_rad = math.radians(sec.chi)
            pts = []
            for xu, yu in upper:
                xs = xu * sec.c
                ys = yu * sec.c
                pts.append((xs * math.cos(chi_rad) / 1000,
                            sec.r / 1000,
                            (xs * math.sin(chi_rad) + ys) / 1000))
            for xl, yl in reversed(lower):
                xs = xl * sec.c
                ys = yl * sec.c
                pts.append((xs * math.cos(chi_rad) / 1000,
                            sec.r / 1000,
                            (xs * math.sin(chi_rad) + ys) / 1000))

            # SW spline from points
            arr_size = len(pts) * 3
            arr = win32.Array(0.0, arr_size - 1)
            for i, (px, py, pz) in enumerate(pts):
                arr[i * 3] = px
                arr[i * 3 + 1] = py
                arr[i * 3 + 2] = pz
            part.SketchManager.CreateSpline(arr)
            part.SketchManager.Insert3DSketch(True)

        # Loft + pattern (practical when called from Windows)

        if output_path:
            os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
            part.SaveAs(output_path)
            return output_path
        return ""
    except Exception as e:
        raise RuntimeError(f"SW modeling failed: {e}")


# ═══════════════════════════════════════════════════════════════
# 完整 Pipeline
# ═══════════════════════════════════════════════════════════════


def design_and_generate(
    Q: float, P: float, n: float,
    airfoil: str = "clark_y",
    material: str = "Q235B",
    output_dir: str = ".",
    gen_macro: bool = True,
    gen_curves: bool = False,
    gen_model: bool = False,
) -> dict:
    """
    完整流程：设计 → 生成 VBA 宏（可选: 曲线/3D 模型）

    Returns:
        {
            "design": AxialFanResult,
            "summary": str,
            "macro_path": str or None,
            "curve_paths": list[str],
            "model_path": str or None,
        }
    """
    from .design import design_axial_fan
    from .params import AxialFanInput

    inp = AxialFanInput(Q=Q, P=P, n=n, airfoil=airfoil, material=material)
    design = design_axial_fan(inp)
    result = {
        "design": design,
        "summary": design.summary,
        "macro_path": None,
        "curve_paths": [],
        "model_path": None,
    }

    os.makedirs(output_dir, exist_ok=True)
    safe = f"Axial_Q{Q:.0f}_P{P:.0f}_n{n:.0f}"

    if gen_macro:
        path = os.path.join(output_dir, f"{safe}.bas")
        with open(path, "w", encoding="utf-8") as f:
            f.write(generate_vba_macro(design))
        result["macro_path"] = path
        print(f"  ✅ VBA Macro: {path}")

    if gen_curves and design.sections:
        loft = generate_blade_loft_profile(design.sections, design.airfoil)
        prefix = os.path.join(output_dir, safe)
        export_loft_sections(loft, prefix)
        result["curve_paths"].append(f"{prefix}_hub_curve.csv")
        result["curve_paths"].append(f"{prefix}_tip_curve.csv")

    if gen_model and HAS_PYWIN32:
        path = os.path.join(output_dir, f"{safe}.SLDPRT")
        build_axial_sw(design, output_path=path)
        result["model_path"] = path

    return result


# ═══════════════════════════════════════════════════════════════
# Test
# ═══════════════════════════════════════════════════════════════

if __name__ == "__main__":
    from .design import design_axial_fan
    from .params import AxialFanInput

    inp = AxialFanInput(Q=20000, P=800, n=1450)
    design = design_axial_fan(inp)
    print(design.summary)

    macro = generate_vba_macro(design)
    with open("/tmp/axial_impeller.bas", "w") as f:
        f.write(macro)
    print(f"\n✅ VBA macro: /tmp/axial_impeller.bas ({len(macro)} chars, {macro.count(chr(10))} lines)")
